Add in initial parser and transpiler code
GDQuest/godot-2d-visual-novel pull request #12
Opened 2021-03-13 18:10 UTC by fsnowdin

Add in the very messy code for the parser and the transpiler.

Related issue (if applicable): #10

2021-03-17 14:51 UTC, NathanLovato requested changes
There's just one change I'd like with the GLOBALS property. You can remove it and store `variables` and `jump_points` in an autoload if that's convenient, otherwise in like `Main.gd` and pass it to `ScenePlayer` instances.

Best not present them as constants here as they're not constant (variables can be any value and change anytime with the player's decisions, jump points get updated with parsed scenes).

I'll change other things myself for the tutorials, like breaking some code into functions, but that's beyond the scope of your job. You did some great work already.

2021-03-17 14:51 UTC, NathanLovato commented on godot/Parser/SceneTranspiler.gd
> +		}
If this is supposed to be available across the game, so shared across all scenes, you shouldn't define the constant here. It's never going to be a global either so I'd use two variables, say, on the main class, or on some singleton. But not on what's supposed to represent a single dialogue tree.

2021-03-17 18:51 UTC, fsnowdin commented on godot/Parser/SceneTranspiler.gd
> +		}
I've moved the `jump_points` somewhere else and used a singleton for handling variables.

2021-03-18 13:28 UTC, merged

2021-03-18 13:29 UTC, NathanLovato commented
Great job! There are some things left to tweak and refactor but it's time to merge already.